# Location of top-level MicroPython directory
MPY_DIR = ../

# Name of module
MOD = native_wav

# Source files (.c or .py)
SRC = write.c

# Architecture to build for (x86, x64, armv6m, armv7m, xtensa, xtensawin)
ARCH = armv7emdp

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
